### ISSUE TITLE
Workflow fails to add a pr to a project

### ISSUE THREAD

**Issue by BobAnkh** [takanabe/add-new-issues-to-project-column#20] opened 2020-07-03 05:40 UTC
I'm tring to add a new pr to a project using your actions but I failed.

Here is my workflow file:

```
name: Add a new PR to the specified project column
on: 
  pull_request:
    types: [opened, reopened]
jobs:
  add-new-PRs-to-project-column:
    runs-on: ubuntu-latest
    steps:
    - name: add-new-prs-to-repository-based-project-column-LinuxCommand
      uses: docker://takanabe/github-actions-automate-projects:v0.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_PROJECT_URL: https://github.com/BobAnkh/LinuxBeginner/projects/1
        GITHUB_PROJECT_COLUMN_NAME: In progress
```

Here is the log of github actions:

```
 add-new-prs-to-repository-based-project-column-LinuxCommand1s
	/usr/local/go/src/runtime/asm_amd64.s:1337
Run docker://takanabe/github-actions-automate-projects:v0.0.1
/usr/bin/docker run --name takanabegithubactionsautomateprojectsv001_720199 --label 87c201 --workdir /github/workspace --rm -e GITHUB_TOKEN -e GITHUB_PROJECT_URL -e GITHUB_PROJECT_COLUMN_NAME -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/LinuxBeginner/LinuxBeginner":"/github/workspace" takanabe/github-actions-automate-projects:v0.0.1
2020/07/03 05:18:03 [INFO] Event name: pull_request
2020/07/03 05:18:03 [INFO] Payload for pull_request extract correctly
2020/07/03 05:18:03 [ERROR] GET https://api.github.com/repos/BobAnkh/LinuxBeginner/projects: 401 Bad credentials []
Failed to get results from GitHub
main.validateGitHubResponse
	/app/main.go:264
main.projectIDByRepo
	/app/main.go:148
main.main
	/app/main.go:61
runtime.main
	/usr/local/go/src/runtime/proc.go:200
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1337
```

Here is the [raw log](https://pipelines.actions.githubusercontent.com/EiteQfHGX3QylQVfW7qtxpN9zZHJSbLWXVnJ9uLPnxhumkGIzi/_apis/pipelines/1/runs/182/signedlogcontent/3?urlExpires=2020-07-03T05%3A39%3A29.7423492Z&urlSigningMethod=HMACV1&urlSignature=fpE140Cq1jABVg5NjKKm5ZgsrI7fYrT5tdJ1hGbgDPQ%3D)

So I'm confused to face this problem. Is there something I forget to configure?

Could you please help me to solve this problem?

Thank you for your time!

**Comment by takanabe** [comment] 2020-07-14 09:44
@BobAnkh 

Hi!

>GitHub Projects belong to organizations, repositories, and users. This GitHub action currently does not support user-based GitHub Project.

This action does not support user-based GitHub Projects because [go-github](https://github.com/google/go-github/pull/1295) didn't support APIs about List user projects and Create a user project when I wrote the actions. 

It's now supported with my PR, so I may support a user-based project as well in my spare time.

**Comment by BobAnkh** [comment] 2020-07-14 10:04
@takanabe 
Thank you for your reply.

But I think my project is a repo-based one. Is there something I got wrong?

I think this error might be caused by that the pr is opened from a forked repo. (I've changed the token to a personal access token but still faced errors)

Also, during the period, I've implemented a action to deal with it myself (but still fails to get triggered by a pr opened from a forked repo to my repo, so I changed the event to trigger this action to solve this problem)

I think this is what you may take into account.

Thank you for your consideration.

**Comment by takanabe** [comment] 2020-07-14 10:14
>I think this error might be caused by that the pr is opened from a forked repo.

ah, yes! this must be the root cause of 401 error.

**Comment by takanabe** [comment] 2021-03-27 06:04
Let me close this issue since I don't think we have the way pass secrets to the forked repository unfortunately and actions cannot solve the issue without GitHub's improvements around secret managements.

**Closed as completed by takanabe** 2021-03-27 06:04 UTC
